onlyBuiltDependencies:
  - "@fortawesome/fontawesome-common-types"
  - "@fortawesome/fontawesome-svg-core"
  - "@fortawesome/free-regular-svg-icons"
  - "@fortawesome/free-solid-svg-icons"
  - "@homebridge/node-pty-prebuilt-multiarch"
  - "@louislam/sqlite3"
  - core-js
  - esbuild
  - vue-demi
