import dayjs from "dayjs";
import "dayjs/plugin/timezone";
import timezones from "timezones-list";
import { currentLocale, localeDirection } from "./i18n";

/**
 * Returns the offset from UTC in hours for the current locale.
 * @param {string} timeZone Timezone to get offset for
 * @returns {number} The offset from UTC in hours.
 *
 * Generated by Trelent
 */
function getTimezoneOffset(timeZone: string): number {
  const now = new Date();
  const tzString = now.toLocaleString("en-US", {
    timeZone,
  });
  const localString = now.toLocaleString("en-US");
  const diff = (Date.parse(localString) - Date.parse(tzString)) / 3600000;
  const offset = diff + now.getTimezoneOffset() / 60;
  return -offset;
}

/**
 * Returns a list of timezones sorted by their offset from UTC.
 * @returns {object[]} A list of the given timezones sorted by their offset from UTC.
 *
 * Generated by Trelent
 */
export function timezoneList(): object[] {
  let result = [];

  for (let timezone of timezones) {
    try {
      let display = dayjs().tz(timezone.tzCode).format("Z");

      result.push({
        name: `(UTC${display}) ${timezone.tzCode}`,
        value: timezone.tzCode,
        time: getTimezoneOffset(timezone.tzCode),
      });
    } catch (e) {
      // Skipping not supported timezone.tzCode by dayjs
    }
  }

  result.sort((a, b) => {
    if (a.time > b.time) {
      return 1;
    }

    if (b.time > a.time) {
      return -1;
    }

    return 0;
  });

  return result;
}

/**
 * Set the locale of the HTML page
 * @returns {void}
 */
export function setPageLocale(): void {
  const html = document.documentElement;
  html.setAttribute("lang", currentLocale());
  html.setAttribute("dir", localeDirection());
}
